### ISSUE TITLE
Error while retrieving a file from AWS S3 with Fog

### ISSUE THREAD

**Issue by bndn** [gzigzigzeo/carrierwave-meta#4]
The uploading of a file to AWS S3 works well, but the retrieving don't. CarrierWave-meta use the method `set_content_type`, from the MimeTypes module, which call the other method `original_filename`, from the File module, but that doesn't exist with Fog.
Why does the method `set_content_type` is called after each retrieving of a file ?

**Comment by nfriend21** [comment]
still happening to me too.

**Comment by torstenb** [comment]
Also just ran into this issue.

**Comment by elliot-nelson** [comment]
Also experiencing this issue running fog 1.28.0, carrierwave 0.10.0, and carrierwave-meta 0.0.5.

It looks like this round of the issue is actually in carrierwave -- pulling from the master branch fixes the issue.  I'm sure this will come out as the stable tagged version in the near future, but in the meantime, just edit your Gemfile as follows:

    gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
